version: "3.8"

services:
  redis:
    image: redis:7-alpine  # Dùng image-alpine cho nhẹ
    container_name: trello-redis-dev
    ports:
      - "6379:6379" # Ánh xạ cổng 6379 của container ra máy thật
    volumes:
      - redis-data:/data # Volume để lưu dữ liệu Redis (persistent)
    restart: unless-stopped

volumes:
  redis-data:
    driver: local